//ACTION TYPES ARE DEFINED AS A STRING CONSTANT
export const PRODUCTOS_LOADING = 'PRODUCTOS_LOADING';
export const ADD_PRODUCTOS = 'ADD_PRODUCTOS';
export const PRODUCTOS_FAILED = 'PRODUCTOS_FAILED';

// export const ADD_COMMENTS = 'ADD_COMMENTS';
// export const COMMENTS_FAILED = 'COMMENTS_FAILED';

// export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
// export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
// export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

// export const PARTNERS_LOADING = 'PARTNERS_LOADING';
// export const ADD_PARTNERS = 'ADD_PARTNERS';
// export const PARTNERS_FAILED = 'PARTNERS_FAILED';

// export const ADD_FAVORITE = 'ADD_FAVORITE';

//WEEK2-TASK3 add Comment from Rating form
export const CREATE_PRODUCT = 'CREATE_PRODUCT';

// export const DELETE_FAVORITE = 'DELETE_FAVORITE'; //Week3